name: Release npm package

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout main
        uses: actions/checkout@main
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: CI
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: ci
      - name: Build
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Tests
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: test
      - name: Release
        run: yarn run semantic-release --branches main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}