name: Release npm package


on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: test
      - run: npx semantic-release --branches main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
