name: Release npm package

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout main
        uses: actions/checkout@main
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "12.19.0"
      - name: Install Yarn
        run: npm install --global yarn
      - name: Setup CI
        run: yarn ci
      - name: Build
        run: yarn build
      - name: Tests
        run: yarn test
      - name: Release
        run: yarn run semantic-release --branches main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}