name: Test npm package

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  release:
    name: PR Testing
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Install Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: "12.19.0"
      - name: Install Yarn
        run: npm install --global yarn@1.22.10
      - name: Setup CI
        run: yarn ci
      - name: Build
        run: yarn build
      - name: Tests
        run: yarn test
