name: Test Package

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  release:
    name: Test Package
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Pull Request Branch
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'
      - name: Remove 'node_modules'
        run: rm -rf node_modules/**
      - name: Install Yarn
        run: npm install --global yarn
      - name: Configure CI
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
